### PR TITLE
TSK-1817: Added received to TaskSummaryImpl constructor.

### PR DESCRIPTION
**Pull request by ensarevlideveloper**
https://sonarcloud.io/summary/new_code?id=ensarevlideveloper_taskana&branch=TSK-1817

---
 
### For the submitter:
- [ ] I updated the [documentation](https://taskana.atlassian.net/wiki/spaces/TAS/overview) and will supply links to the specific files
- [X] I did not update the [documentation](https://taskana.atlassian.net/wiki/spaces/TAS/overview)
- [X] I included a link to the [SonarCloud branch analysis](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1019969636/SonarCloud+Integration)
- [ ] I added a description of changes on the [current release notes](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1281392672/Current+Release+Notes+Taskana)
- [X] I did not update the [current release notes](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1281392672/Current+Release+Notes+Taskana)
- [X] I put the ticket in review
- [ ] After integration of the pull request, I verified our [bluemix test environment](http://taskana.mybluemix.net/taskana) is not broken

### Verified by the reviewer:
- [ ] Commit message format → TSK-XXX: Your commit message.
- [ ] Submitter's update to [documentation](https://taskana.atlassian.net/wiki/spaces/TAS/overview) is sufficient
- [ ] SonarCloud analysis meets our standards
- [ ] Update of the [current release notes](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1281392672/Current+Release+Notes+Taskana) reflects changes
- [ ] PR fulfills the ticket
- [ ] Edge cases and unwanted side effects are tested
- [ ] Readability

### CODE REVIEW

**Review by holgerhagen — APPROVED** [review]

**Review by gitgoodjhe — DISMISSED** [review]
Please also enhance TaskModelsCloneTest.testCloneInTask with the "received" property

**Comment by ensarevlideveloper** [comment]
*bump* please review again ^^

**Comment by mustaphazorgati** [comment]
> *bump* please review again ^^

Tip: message the reviewer directly

**Review by holgerhagen — APPROVED** [review]

**Comment by mustaphazorgati** [comment]
Why did this get merged?
@gitgoodjhe comment regarding the TaskModelsCloneTest is still not adjusted.
Therefore the content of this PR is not tested

**Pull request merged**
