### PR TITLE
Java17

### PR DESCRIPTION
**Pull request by arolfes**
All Tasks to migrate to Java 17

---
Release Notes:

```

```
 
### For the submitter:
- [ ] I updated the [documentation](https://taskana.atlassian.net/wiki/spaces/TAS/overview) and will supply links to the specific files
- [ ] I did not update the [documentation](https://taskana.atlassian.net/wiki/spaces/TAS/overview)
- [ ] I included a link to the [SonarCloud branch analysis](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1019969636/SonarCloud+Integration)
- [ ] After integration of the PR, I added a description of changes on the [current release notes](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1281392672/Current+Release+Notes+Taskana)
- [ ] I did not update the [current release notes](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1281392672/Current+Release+Notes+Taskana)
- [ ] I put the ticket in review
- [ ] After integration of the pull request, I verified our [bluemix test environment](http://taskana.mybluemix.net/taskana) is not broken

### Verified by the reviewer:
- [ ] Commit message format → (Closes) #<Issue Number>: Your commit message. i.e. Closes #2271: Your commit message.
- [ ] Submitter's update to [documentation](https://taskana.atlassian.net/wiki/spaces/TAS/overview) is sufficient
- [ ] SonarCloud analysis meets our standards
- [ ] Update of the [current release notes](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1281392672/Current+Release+Notes+Taskana) reflects changes
- [ ] PR fulfills the ticket
- [ ] Edge cases and unwanted side effects are tested
- [ ] Readability

### CODE REVIEW

**Comment by ryzheboka** [comment]
Hi @arolfes ,
thanks for adding a README to the taskana-cdi module! There are lots of changes in this module. Have you manually set up the Wildfly Application and tested if it works?

**Comment by arolfes** [comment]
> Hi @arolfes , thanks for adding a README to the taskana-cdi module! There are lots of changes in this module. Have you manually set up the Wildfly Application and tested if it works?

Hallo @ryzheboka ,

To be honest: I haven't installed and configured the Wildfly Server on my machine directly. Because it is not needed. 

I changed from thorntail to arquillian because thorntail is end-of-life. See https://thorntail.io/

the maven arquillian plugin does the following:
1. downloading specified wildfly version
2. extract the version to specific directory
3. copy configuration files to necessary places of wildfly-server
4. deploy the app
5. starting the tests

The only changes to the tests where the deployment and the URL, no logic was changed or something else. 

The changes came with this PR: https://github.com/Taskana/taskana/pull/2203

What does it mean: The application `taskana-cdi` and `taskana-cdi-example` will be deployed to a running wildfly server and then the REST-Endpoints from TASKANA-cdi are called. Only the endpoints are called, where tests exists. If you need more tests, you should implement them.

After swithing from thorntail to arquillian I needed to switch from wildfly 15 to 25. Because 25 is the minimal version which runs with JDK 17. Please see https://www.mastertheboss.com/jbossas/wildfly-8/choosing-the-jdk-for-wildfly-and-jboss-eap-7/

And then the the changes to `taskana-rest-spring-example-wildfly` and `taskana-cdi` are very small

* change the wildfly-server version
* fix the config

The changes came with this PR: https://github.com/Taskana/taskana/pull/2207

What does it mean? The application `taskana-rest-spring-example-wildfly` will be deployed to a running wildfly server and then the REST-Endpoints from TASKANA are called. Only the endpoints are called, where tests exists. If you need more tests, you should implement them.

As  the `taskana-rest-spring-example-wildfly` is only an example I can not say if you can copy the configuration directly to your customer setup.

I hope my answer helps you to understand the changes. Please see also that there are 4 commits in this PR. 3 commits have been another PR. This makes your review a bit easier.
1. https://github.com/Taskana/taskana/pull/2203
2. https://github.com/Taskana/taskana/pull/2207
3. https://github.com/Taskana/taskana/pull/2213

Best Regards
Alex

**Comment by arolfes** [comment]
Hello @ryzheboka , @gitgoodjhe , @mustaphazorgati ,
For your Information: I just rebased the JAVA17 branch with current master from TASKANA and force pushed the changes.

**Comment by arolfes** [comment]
Hello @ryzheboka , @gitgoodjhe , @mustaphazorgati ,
maybe you have time this week to have a look on this PR.
Thanks a lot

**Review by gitgoodjhe — APPROVED** [review]

**Pull request merged**
