### PR TITLE
TSK-975: Remove unnecessary initializers

### PR DESCRIPTION
**Pull request by BVier**

### CODE REVIEW

**Comment by BVier** [comment]
TSK-977 is based upon this task.
I splited them because TSK-977 is about the enforcing of linting, not the correction of older linting errors

**Comment by BVier** [comment]
But in the end you're right - if you approve TSK-977 this PR is redundant.

**Comment by benjamineckstein** [comment]
so please close one of these two prs. I will review the other one again then. Also please mark discussions as resolved if this point is no longer valid.

**Comment by benjamineckstein** [comment]
included in TSK 977 PR

**Pull request closed without merging**
