### PR TITLE
TSK-1760, TSK-1770: Improved admin UI performance and Query Paging now returns empty, when non existing Page is requested

### PR DESCRIPTION
**Pull request by Tristan2357**
https://sonarcloud.io/summary/new_code?branch=TSK-1760&id=Tristan2357_taskana

1760: 
 * A virtually scrolling list was used to display the distribution target lists to improve performance.
 * The workbasket store was reworked to introduce paging of the distribution target lists, to further improve performance.

---
 
### For the submitter:
- [ ] I updated the [documentation](https://taskana.atlassian.net/wiki/spaces/TAS/overview) and will supply links to the specific files
- [x] I did not update the [documentation](https://taskana.atlassian.net/wiki/spaces/TAS/overview)
- [x] I included a link to the [SonarCloud branch analysis](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1019969636/SonarCloud+Integration)
- [x] I added a description of changes on the [current release notes](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1281392672/Current+Release+Notes+Taskana)
- [ ] I did not update the [current release notes](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1281392672/Current+Release+Notes+Taskana)
- [x] I put the ticket in review
- [ ] After integration of the pull request, I verified our [bluemix test environment](http://taskana.mybluemix.net/taskana) is not broken

### Verified by the reviewer:
- [x] Commit message format → TSK-XXX: Your commit message.
- [ ] Submitter's update to [documentation](https://taskana.atlassian.net/wiki/spaces/TAS/overview) is sufficient
- [x] SonarCloud analysis meets our standards
- [x] Update of the [current release notes](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1281392672/Current+Release+Notes+Taskana) reflects changes
- [x] PR fulfills the ticket
- [x] Edge cases and unwanted side effects are tested
- [x] Readability

### CODE REVIEW

**Review by cnguyen-de — APPROVED** [review]
if cloneDeep is the only function from lodash being used, then I'd recommend importing clonedeep directly instead of whole lodash library. 

https://www.npmjs.com/package/lodash.clonedeep

**Review by mustaphazorgati — CHANGES_REQUESTED** [review]
Please squash the commits so that we only have two :)

**Comment by Tristan2357** [comment]
@cnguyen-de I looke into this and use of modular lodash package is discouraged and support for it will be removed in the next mayor version.

**Comment by Tristan2357** [comment]
@mustaphazorgati done

**Review by mustaphazorgati — APPROVED** [review]

**Pull request merged**
