### PR TITLE
TSK-1402 Add support for Oracle DB

### PR DESCRIPTION
**Pull request by yregaieg**
This is the ground work for adding support for Oracle to Taskana.

Not yet addressed in this PR:

- [ ] Documentation on how to set up a sample Oracle XE DB instance for running taskana
- [ ] CI/CD tests against Oracle DB

### CODE REVIEW

**Comment by mustaphazorgati** [comment]
Hey @yregaieg,
with #1291 I added and moved some modules and classes. Do you want me to help you out keeping this PR up-to-date?

**Comment by yregaieg** [comment]
Hey @mustaphazorgati !

Thanks for the heads-up, I am currently super-busy with other priorities, I will have a look later this week or maybe next week :-)

**Comment by mustaphazorgati** [comment]
Hey there!
What's the status?

**Comment by yregaieg** [comment]
@mustaphazorgati I still haven't had the time to get back to taskana as my priorities shifted a bit, I will try to rebase in the coming couple of weeks :-)

**Comment by mustaphazorgati** [comment]
Alright. just a heads up: we upgraded to jdk11 for development. 

Runtime support is still jdk8+

**Comment by mustaphazorgati** [comment]
Let me know if you need any help

**Comment by mustaphazorgati** [comment]
hey @yregaieg, 
we decided to close this PR until we receive an update from you sometime in the future :) Again, if you need help you know how to reach me ;)

**Pull request closed without merging**
